### PR TITLE
Add rouge syntax highlighting

### PR DESCRIPTION
**Pull request by jelaniwoods**
In combination with #93 

This PR adds the `rouge` gem for Ruby syntax highlighting.

Other changes:
- Adds a `rouge` generated SCSS file and imports it.
- Uses `rouge` in the Kramdown parsing.

Example in plain text:
\~\~\~ruby
3.times do |block|
  p block + 2
end
\~\~\~

checkins-pr-ruby-syntax

### CODE REVIEW

**Comment by LoganDSPrice** [comment]
Where did you find that stylesheet? I couldn't find any reference to that in the docs! I dug around in Chapters and Rouge and Kramdown and basically found similar stylesheets but I didn't find any install commands or anything like that!

**Comment by jelaniwoods** [comment]
@LoganDSPrice Yeah it's pretty hidden. I took it from [chat](https://github.com/firstdraft/chat/blob/7a910363a54e3b88fd8790e3fde8a3d473c93a73/app/assets/stylesheets/rouge_style.scss) but I remember I had to first generate it with the [`rougify` command](https://github.com/rouge-ruby/rouge#command-line) and gave it `github` for the theme. Then I converted it into a SCSS file and imported it to the project. There might be a better way to do this but I didn't find anything when I looked before.

**Comment by LoganDSPrice** [comment]
wtf

**Comment by LoganDSPrice** [comment]
Awesome! Thanks!

**Comment by jelaniwoods** [comment]
@LoganDSPrice I just found this [old issue](https://github.com/rouge-ruby/rouge/issues/343#issuecomment-219926122) which might be better? Idk

**Pull request merged**
